name: Test TensorSensor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
		python -m pip install --upgrade pip
                python setup.py install

    - name: Test with pytest
      run: |
        pip install pytest
        pytest testing/test_parser.py 
